# Generated by Django 3.0.6 on 2020-05-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='VALID PYTHON', upload_to='photos/'),
        ),
    ]
